### ISSUE TITLE
数据集更改

### ISSUE THREAD

**Issue by JiuJiaozgmzb** [JackHCC/Chinese-Text-Classification-PyTorch#9]
如果想要更换数据集，需要bert等预训练结合的模型更改词向量等文件吗？还有什么文件需要修改

**Comment by JiuJiaozgmzb** [comment]
还有一般test是不是不带标签，只有dev和train才有标签

**Comment by JackHCC** [comment]
> 还有一般test是不是不带标签，只有dev和train才有标签

是的

**Comment by JackHCC** [comment]
> 如果想要更换数据集，需要bert等预训练结合的模型更改词向量等文件吗？还有什么文件需要修改

只需要把数据集改成相同的结构即可

**Comment by JiuJiaozgmzb** [comment]
可是本项目的代码好像需要test带标签才可以
